# Generated by Django 5.2 on 2025-05-18 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apa_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="value",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
