# Generated by Django 5.2 on 2025-05-19 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apa_core", "0002_embedding_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="match_with",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
