# Generated by Django 5.2 on 2025-11-17 01:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FetchedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                (
                    "source_url",
                    models.URLField(blank=True, db_index=True, max_length=2000),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'web', 'pdf', 'docx', 'api'",
                        max_length=100,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=300)),
                (
                    "language",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Optional vector embedding as list of floats",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="generate_store.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "fetched_at"],
                        name="generate_st_topic_i_a9f9f5_idx",
                    ),
                    models.Index(
                        fields=["source_url"], name="generate_st_source__d0afc8_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="generate_st_content_b9ad29_idx"
                    ),
                ],
            },
        ),
    ]
